### PR TITLE
Update dynamo sub module

### PR DESCRIPTION
**Pull request by JaekwanLee**
## Description of the change

> Updating aiq-dynamo-python submodule

## Type of change
- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Comment by spenceraiq** [comment]
LG, I would recommend that we add the python-tools bump to the PR as soon as that PR is approved. Some of the requirements included in this bump may depend on changes to the python-tools submodule.

**Comment by JaekwanLee** [comment]
@spenceraiq I don't think the dynamo sub-module is dependent on the python-tool module. I see it is being used by the airflow repo but couldn't find any other usage. These two submodules are pretty independent.

**Comment by spenceraiq** [comment]
@JaekwanLee An excellent point. The concern that I have is that since airflow installs both the dynamo and tools dependencies into the same python environment, and since dynamo and tools have some of the same module dependencies and sub-dependencies, that the version changes that are made and merged in the most recent version of dynamo may cause some breaking imports in the airflow project since the python-tools dependencies are still pending approval.

**Comment by JaekwanLee** [comment]
@spenceraiq I see the other PR in python-tool and requirement.txt updated in dynamo repo that would come along with this change. Since my change is not urgent, I can wait until you guys merge both repo together. Will close this PR

**Pull request closed without merging**
