### PR TITLE
Release/0.90.7 arvest

### PR DESCRIPTION
**Pull request by akspha**

### CODE REVIEW

**Comment by JaekwanLee** [comment]
is this uat -> master release?

**Comment by akspha** [comment]
> is this uat -> master release?

yes,  @mchow  had closed https://github.com/AgentIQ/aiq-airflow/pull/11

**Comment by mchow** [comment]
Yea there a bunch of issues, I just rolled back the image

**Comment by mchow** [comment]
i closed this because there was a bunch of issue's. we also probably dont need airflow anymore since we have removed the whitelist

**Pull request closed without merging**
