### PR TITLE
Use python instead of python3

### PR DESCRIPTION
**Pull request by JaekwanLee**
It seems bash command needs to use python instead of python 3

### CODE REVIEW

**Comment by akspha** [comment]
> It seems bash command needs to use python instead of python 3

does that run python ?
our scripts could break if so, since they are in python3
do we need to install python3 on airflow instead?

**Comment by JaekwanLee** [comment]
Right. I had issues on customer events failing. The pr is to make python script consistent across dags. Also Our all python image uses python 3.6 as default unlike individual's laptop configuration.
```
FROM agentiq/app-python-3.6:v1
```

@mchow I found the issue. This is stats env variable not set problem in airflow environment.

**Comment by mchow** [comment]
> Right. I had issues on customer events failing. The pr is to make python script consistent across dags. Also Our all python image uses python 3.6 as default unlike individual's laptop configuration.
> 
> ```
> FROM agentiq/app-python-3.6:v1
> ```
> 
> @mchow I found the issue. This is stats env variable not set problem in airflow environment.

what is the name of it?

**Comment by mchow** [comment]
yes, we have been on python3.6.x for a while, you manage different versions of python, i create a best practice guide https://docs.google.com/document/d/1MHbAlBTrrsf5tL4B33cNgVIVbDxdPVU_UqL-BspMPUE/edit

**Pull request merged**
